server:
  port: 8080
mysql:
  dbMysqlAddress: [ mysql:3306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root  #mysql用户名，建议修改
  dbMysqlPassword: 123456  # mysql密码，建议修改
  dbMysqlDatabaseName: zf_db #默认即可
  dbMaxOpenConns: 100
  dbMaxIdleConns: 10
  dbMaxLifeTime: 5
  logLevel: 1 #1=slient 2=error 3=warn 4=info
  slowThreshold: 500
redis:
  dbAddress: [ redis:6379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbUserName:     #only redis version 6.0+ need username
  dbPassWord:  #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关
log:
  storageLocation: ./logs/
  rotationTime: 24
  remainRotationCount: 2 #日志数量
  #日志级别 6表示全都打印，测试阶段建议设置为6
  remainLogLevel: 6
  elasticSearchSwitch: false
  elasticSearchAddr: [ elasticsearch:127.0.0.1:9201 ]
  elasticSearchUser: ""
  elasticSearchPassword: ""
